// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AnswerInput struct {
	SurveyID   uint64   `json:"surveyId"`
	QuestionID uint64   `json:"questionId"`
	Answer     *string  `json:"answer"`
	Options    []string `json:"options"`
}

type QuestionBlank struct {
	ID       uint64   `json:"id"`
	Type     string   `json:"type"`
	Question string   `json:"question"`
	Options  []string `json:"options"`
}

type SurveyBlank struct {
	SurveyID    uint64           `json:"surveyId"`
	Description string           `json:"description"`
	Questions   []*QuestionBlank `json:"questions"`
}
